<?php require VIEWS_PATH . '/admin/includes/header.phtml'; ?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Criar Produto</h2>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
        </div>
    </div>

    <div class="row">
        <form action="<?= HOME; ?>/admin/products/edit/<?= $this->product['id']; ?>" method="post" enctype="multipart/form-data">
            <div class="col-md-12">
                <div class="form-group">
                    <label>Nome do Produto</label>
                    <input type="text" class="form-control" name="name" value="<?= $this->product['name']; ?>">
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <label>Descrição</label>
                    <input type="text" class="form-control" name="description" value="<?= $this->product['description']; ?>">
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <label>Conteúdo</label>
                    <textarea name="content" class="form-control"><?= $this->product['content']; ?></textarea>
                </div>
            </div>

            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Preço</label>
                            <input type="text" class="form-control" name="price" value="<?= number_format($this->product['price'], 2, ',', '.'); ?>">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <label>Status do Producto</label>
                        <select name="is_active" id="" class="form-control">
                            <option value="1" <?php if ($this->product['is_active']) : ?> selected<?php endif; ?>>Activo</option>
                            <option value="0" <?php if (!$this->product['is_active']) : ?> selected<?php endif; ?>>Inactivo</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <label>Seleccione as imagens do produto</label>
                    <input type="file" name="images[]" multiple class="form-control">
                </div>
            </div>

            <div class="col-md-12">
                <button type="submit" class="btn btn-lg btn-success">Actualizar Produto</button>
            </div>
        </form>
    </div> <!-- Fechamento do row dos inputs -->
</div>
<?php require VIEWS_PATH . '/admin/includes/footer.phtml'; ?>